### ISSUE TITLE
Other plots

### ISSUE THREAD

**Issue by fmaussion** [finnwimberly/glacial_runoff_mapping#2]
The app currently is very much tailored to demonstrate the differences between the models, which is very useful and fits the paper very well. However other users (say, ICCI) will have interest in a few other plots which I think are relatively easy to add without jeopardizing the original intent of the app. A few ideas:

- [x] When selecting one model in the main frame, the resulting plots in the "Basin information" box could show all SSPs for that model instead of one single line (Model for 1 currently selected SSP). This way a user can explore the influence of SSPs as well.
- [x] If possible, it would be great to have the option to see relative changes as well (less focus on absolute values) -> useful for people less interested in inter-model differences and absolute values.

More longer term and out of scope, but of course OGGM (or pygem maybe?) have the monthly components and melt components available, which would be a fantastic addition one day. Something to think about, perhaps in a companion app focussed on OGGM output already.

**Comment by finnwimberly** [comment]
Created and uplaoded new figures which have two panels. If using the "multi-model median" input the panels show annual runoff volume (righthand subplot) and percent change in runoff compared to historical mean (lefthand subplot) for all three models and the selected SSP. If using a single glacier model as the input, the righthand subplot shows the annual runoff volume (for only that model as well as the selected SSP) while the lefthand subplot shows projections for all 4 SSPs given by a 20-year rolling mean.
